MADNESS: 1dharmonic.cc File Reference
1dharmonic.cc File Reference
#include <madness/mra/funcdefaults.h>
#include <madness/mra/function_factory.h>
#include <madness/mra/legendre.h>
#include <madness/mra/mra.h>
#include <madness/mra/funcplot.h>
#include <madness/mra/nonlinsol.h>
#include <madness/mra/operator.h>
#include <madness/world/worldmpi.h>
Classes
struct GuessFunction< N >
struct num< N >
Functions
double energy (World &world, const Function< double, 1 > &phi, const Function< double, 1 > &V)
template<std::size_t N, typename F >
void for_ (F func)
template<class F , std::size_t... Is>
void for_ (F func, std::index_sequence< Is... >)
template<int N>
void generate_and_solve (World &world, const Function< double, 1 > &V)
int main (int argc, char **argv)
void plot (const char *filename, const Function< double, 1 > &f)
double potential (const Vector< double, 1 > &r)
Variables
const double DELTA = 7.0
const double L = 10.0
Function Documentation
energy()
double energy (World & world, const Function< double, 1 > & phi, const Function< double, 1 > & V)
References madness::inner(), and V().
Referenced by generate_and_solve().
for_() [1/2]
template<std::size_t N, typename F > void for_ (F func)
References for_(), and madness::func().
for_() [2/2]
template<class F , std::size_t... Is> void for_ (F func, std::index_sequence< Is... >)
References madness::func().
Referenced by for_().
generate_and_solve()
template<int N> void generate_and_solve (World & world, const Function< double, 1 > & V)
References DELTA, e(), energy(), madness::FunctionFactory< T, NDIM >::f(), madness::filename, N, madness::detail::norm(), madness::Function< T, NDIM >::norm2(), op(), madness::plot(), madness::print(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::Function< T, NDIM >::truncate(), madness::NonlinearSolverND< NDIM >::update(), and V().
Referenced by main().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, e(), madness::FunctionFactory< T, NDIM >::f(), madness::finalize(), generate_and_solve(), madness::initialize(), L, madness::plot(), potential(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), thresh, V(), and madness::wall_time().
plot()
void plot (const char * filename, const Function< double, 1 > & f)
References madness::f, madness::filename, L, lo, and madness::plot_line().
potential()
double potential (const Vector< double, 1 > & r)
References DELTA.
Referenced by apply_potential(), madness::GTHPseudopotential< Q >::apply_potential(), MiniDFT::apply_potential(), madness::GTHPseudopotential< Q >::apply_potential_simple(), madness::Solver< T, NDIM >::build_fock_matrix(), compute_energy(), compute_fock_matrix(), DF::diagonalize(), madness::Znemo::hcore_guess(), madness::Solver< T, NDIM >::initial_guess(), madness::SCF::initial_guess(), madness::CCIntermediatePotentials::insert(), main(), DF::make_fermi_potential(), DF::make_gaussian_potential(), madness::Solver< T, NDIM >::print_fock_matrix_eigs(), madness::Solver< T, NDIM >::print_potential_matrix_eigs(), test_converged_function(), test_convergence(), and test_slater_exchange().
Variable Documentation
DELTA
const double DELTA = 7.0
Referenced by generate_and_solve(), and potential().
L
const double L = 10.0
Referenced by main(), and plot().